name: Backend CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up JDK 23 with distribution
      - name: Set up JDK 23 (Zulu)
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adoptopenjdk'

      # Build the backend JAR using Gradle
      - name: Build Backend with Gradle
        run: ./gradlew build

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image for Backend
      - name: Build Docker Image for Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:$GITHUB_SHA .

      # Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:$GITHUB_SHA
